

<html lang="pt-br">
  <head>
 
    <meta charset="utf-8" />
    <title>Receitas Ipanema </title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <style>
      body{
        background-color:#808e9b;
      }
      .card-login {
      
        border: 2px solid #3c40c6;
    
        padding: 30px 0 0 0;
        width: 350px;
        margin: 0 auto;
        margin-top: 25px;
      }
      .login{
          background-color: #d2dae2;
      }

    </style>
  </head>

  <body>

    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">
      <i class="fas fa-glasses "></i>
        Otica Ipanema
      </a>
    </nav>

    <div class="container">    
      <div class="row ">

        <div class="card-login login">
          <div class="card ">
            <div class="card-header" style="text-align: center;">
              <h4>Login</h4>
            </div>
            <div class="card-body login">
              <form action="/autenticar" method="post">
                <div class="form-group">
                  <input name="email" type="email" class="form-control" placeholder="E-mail">
                </div>
                <div class="form-group">
                  <input name="senha" type="password" class="form-control" placeholder="Senha">
                </div>

                <?php if(isset($_GET['login']) && $_GET['login'] == 'erro'){?>

                <div class="text-danger">
                  Usuário ou senha inválido(s)
                </div>

                <?php } ?>
                <?php if(isset($_GET['login']) && $_GET['login'] == 'erro2'){?>

                <div class="text-danger">
                  Por favor, faça login antes de acessar as páginas protegidas
                </div>

                <?php } ?>

                <button class="btn btn-lg btn-info btn-block" type="submit">Entrar</button>
              </form>
            </div>
          </div>
        </div>
    </div>
  </body>
</html>